services:
  adminjack:
    build: .
    container_name: adminjack
    ports:
      - "8000:8000"
    volumes:
      - ./event_details.json:/app/event_details.json
      - ./uploads:/app/uploads
      - ./.env:/app/.env
      - ./token.json:/app/token.json
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
